"""add sources to chat messages

Revision ID: f6b62ddf19dd
Revises: 26e1b178b667
Create Date: 2026-08-11 15:19:44.308097

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6b62ddf19dd"
down_revision: Union[str, Sequence[str], None] = "26e1b178b667"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("chat_messages",sa.Column
        ("sources",sa.JSON(),nullable=True,),
    )

    op.execute(
        "UPDATE chat_messages SET sources = '[]' WHERE sources IS NULL"
    )

    op.alter_column(
        "chat_messages",
        "sources",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'sources')
    # ### end Alembic commands ###
